Task#2 html
fineshtein/HTML pull request #9
Opened 2020-04-25 13:45 UTC by fineshtein

Добрый день, 
отправляю вступительное задание по HTML

С уважением,
Алексей

2020-05-14 21:13 UTC, SKryzhantovskiy requested changes
В целом идете в правильном направлении))) главное не останавливаться и все получится.
Я в феврале когда делал это задание наворотил в нем, особенно в css, аж показывать стыдно))) сейчас переверстывал перед отправкой имея уже багаж знаний. 
В html не хватает семантики, хотябы тегов заголовков.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +	<link rel="stylesheet" type="text/css" href="./styles/middle.css">
Здесь, если делаете деление стилей по файлам css, лучше тогда делить полностью на все блоки. То есть отдельно для header, footer, baner, article и т.д. так будет проще читать их и разобраться

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +			<div class="logo grey"> </div>
Здесь располагается логотип и его лучше вставить тегом img внутри div

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<div class="page grey"></div>
Это по задумке ссылки на другие страницы, в блоках не хватает ссылок. Также этот элемент можно сделать через список в одном блоке, тогда его будет легче спозиционировать.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<button class="button black">black button</button>
Опять же для лучшего позиционирования лучше обернуть данные кнопки в блок.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<div class="banner_header btext">Banner Header</div>
Здесь не хватает тега h1 как главного заголовка страницы.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_text left">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita
хедер, для семантики, нужно обернуть в тег h2.
для самого текста можно не создавать отдельного дива, а обенруть в тег "р"

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +					<label for="email"> <div class="button black lbl">fill button  </div></label>
сюда нужно вместо дива нужно вставлять либо input с типом "submit" либо кнопку

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_rectangle grey"></div>
Этот элемент является картинкой, желательно ее еще и вставить в ссылку, это улучшит юзабилити страницы. Так, например, если Вы прочтете заголовок статьи и часть ее содержимого, если статья заинтересовала и Вы захотите продолжить ее чтение, то скорей всего нажмете на картинку к статье чтобы приступить к ее прочтению полностью.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +					<div class="a_rect grey"></div>
в этом месте аналогично с первым артиклем

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +		<div class="footer grey">
В футере аналогично хедеру лого и ссылки на страницы необходимо выполнить по другому.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +					<a href="#"> <img src="./img/twit.png" alt="twitter_logo"/> </a>
Здесь молодец, хорошо сделано.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +	color: #1C1E20;
Не стоит задавать сразу фон для всей страницы, так как в разных блоках он может быть разным и потом придется переназначать. Аналогично и с цветом шрифта.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +	height: 100vh;
Такое указание высоты подойдет для отдельно взятых блоков, но не для всего тела страницы.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +.desktop a {
Ссылки нужно стилизовать непосредственно в том месте где они располагаются, так как в разных местах они могут быть с разными стилями.

2020-05-14 21:13 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/nav_foot.css
> +}
Эти два выражения можно сократить в одно используя псевдокласс :not. Выглядеть будет следующим образом:
.pages_2 .page:not(:last-child){
margin-right: 40px;
}

2020-05-15 09:48 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +	<link rel="stylesheet" type="text/css" href="./styles/middle.css">
Привет)
По семантике спасибо за замечание, так и знач, что первым вылезет )) поправлю
А вот касательно css для footer  и header не совсем согласен, потому что блоки там фактически одинаковые, поэтому решил их объединить в один файл. Поэтому, если не будешь против, не буду его менять

2020-05-15 09:50 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +			<div class="logo grey"> </div>
хм... а я вот в своем ревью, наоборот, попросил исправить на круглый див. Картинку-то всегда успеется вставить, это проще, на мой взгляд. Спорный момент, как и по поводу картинок статей. С картинками же, на мой взгляд, проще работать, чем с блоками

2020-05-15 09:50 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<div class="page grey"></div>
Ок, попробую еще так для практики )

2020-05-15 09:51 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<button class="button black">black button</button>
А смыл лишние блоки? Вроде как увеличение размера и снижение производительности?

2020-05-15 09:51 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<div class="banner_header btext">Banner Header</div>
Ок, принято

2020-05-15 09:51 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +					<a href="#"> <img src="./img/twit.png" alt="twitter_logo"/> </a>
Ой, спасибо, приятно )

2020-05-15 09:52 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +	color: #1C1E20;
А это, чтобы не задавать потом отдельно блокам белый. Поэтому сделал белый, как базовый, и потом уточняю для отдельных элементов. Логика такая. Здесь бы узнать, как правильно)

2020-05-15 09:55 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +	height: 100vh;
100vh? у нас в уроках было указание 100vh для contenta, Марина делала, если правильно помню. Если основной блок должен быть на 100% видимой области, почему так нельзя сделать?

2020-05-15 09:56 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +.desktop a {
А если они везде одинаковые, зачем делать стиль для каждой? Поясни тогда, почему нужно так, как ты сказал. Не очень согласен

2020-05-15 09:58 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/nav_foot.css
> +}
Вот тут спасибо, не знал ) использую

Мы ведь на уроках для последнего всегда задавали отдельным элементом. Для лучшей читабельности, вроде как?

2020-05-15 10:24 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_text left">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita
Принято

2020-05-15 10:26 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +					<label for="email"> <div class="button black lbl">fill button  </div></label>
А зачем? Этот div вспомогательный, для позиционирования
Ниже есть нужный input, только тип нужно на е-мэйл поменять

2020-05-15 10:29 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_rectangle grey"></div>
Уже выше отмечал.. не совсем соглашусь
На усмотрение проверяющего)

2020-05-15 10:30 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +					<div class="a_rect grey"></div>
Ок, принято, по семантике согласен, не доработал

2020-05-15 10:30 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +		<div class="footer grey">
Согласен, исправляю

2020-05-16 21:02 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +	<link rel="stylesheet" type="text/css" href="./styles/middle.css">
ок, здесь оставь. но в будущем лучше если разносить стили, то полностью по отдельным файлам

2020-05-16 21:07 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +			<div class="logo grey"> </div>
Представь, что отверстал страницу для продакшена и следующее звено это человек, который будет наполнять страницу контентом. В случае с просто круглым дивом залитым цветом ему самостоятельно придется менять часть кода, а если он не разбирается? Гораздо проще ведь ему будет закинуть фаил в папку img названый определенным именем и он встанет на свое место.

2020-05-16 21:22 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<button class="button black">black button</button>
проще управлять элементами будет. блок нужен не для каждой кнопки, а один для обеих. так ты сможешь их обе передвинуть в нужное место с меньшими затратами по времени на написание кода

2020-05-16 21:24 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +					<label for="email"> <div class="button black lbl">fill button  </div></label>
я имею в виду fill button

2020-05-16 21:25 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_rectangle grey"></div>
Александр, нужно ваше судейское мнение, если читаете

2020-05-16 21:30 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +	color: #1C1E20;
Здесь так же как и с ссылками. зачем задавать общий стиль если его потом менять нужно будет много где. К тому же дизайнеры могут менять цвет блоков, и в итоге останется только один белый на всю страницу, а стиль с белым фоном задан для всего

2020-05-16 21:34 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +	height: 100vh;
данный класс задан для всей страницы. тоесть ты всю страницу делаешь на высоту экрана, а потом блоки перерисовываешь. так допустимо будет сделать для отдельно взятого блока станицы, например банер или артикле сделать по высоте равной высоте экрана, но не весь сайт

2020-05-16 21:34 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/main.css
> +.desktop a {
В одном из дз я задал общий размер шрифта на что Александр мне ответил "В данном случае задавать для всего контента font-size нормально, но в больших проектах лучше это делать точечно, так как могут быть проблемы при разработке, прийдется перебивать через !important, а это дурной тон." Думаю здесь аналогичная ситуация.

2020-05-17 07:31 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +	<link rel="stylesheet" type="text/css" href="./styles/middle.css">
Решил не спорить, мне нравится работать с кодом, поэтому даже такая маленькая практика полезна ) спасибо за помощь, очень оценил )

2020-05-17 07:32 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +			<div class="logo grey"> </div>
Убедил, поправил все блоки на картинки

2020-05-17 07:37 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<button class="button black">black button</button>
В целом согласен и в задании добавил общий div для кнопок, но у меня позиционировании через родительский элемент задано, поэтому не так критично, на мой взгляд

2020-05-17 07:38 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<div class="a_rectangle grey"></div>
Сделал все картинками для разнообразия, теперь у меня 2 варианта есть )

2020-05-17 07:40 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +	color: #1C1E20;
Вот, что значит недостаток практической работы у меня,.. ) когда не сталкивался с такими вещами, не учитываешь, спасибо)

2020-05-17 07:43 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +	height: 100vh;
Возможно ты и прав, хотя этот стиль пишу обычно для удобства последующего позиционирования для начала работы. в итоге он не сильно нужен оказывается, поэтому убрал

2020-05-17 07:44 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/main.css
> +.desktop a {
А мне, кстати, наоборот писал, что, если одинаковые элементы, то можно общее свойство использовать )) наверное, в данном задании это не столько критичное замечание )

2020-05-17 08:32 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +			<div class="logo grey"> </div>
У самого опыт такой же)
Картинку именно в див и нужно вставлять.

2020-05-20 20:35 UTC, SKryzhantovskiy reviewed
исправляй эти комментарии, остальное все нормально

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<a href="#"> <nav class="page grey"> </nav> </a>
Нужно чтобы ссылка в нав вставлялась, а не наоборот. Тэг нав определяет навигацию и в него вставляются ссылки. В телеграмм отправил конструкцию

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +				<a href="#"><nav class="page white"></nav></a>
Здесь аналогично хедеру

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +						<label for="email"> <div class="button black lbl">fill button  </div></label>
Здесь кнопку так и не добавил

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/index.html
> +		<main class="articles_low">
Тег main предназначен для основного содержимого страницы и на странице данный тег может находится только один, не допустимо использовать несколько раз данный тег. Можно обернуть либо в <article>, либо просто в <section>

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/middle.css
> +	content: 'ᐳ ᐳ'; }
Эти строчки точно здесь должны быть? в html я не нашел элемента с классом hide

2020-05-20 20:35 UTC, SKryzhantovskiy commented on IcomingTest_HTML_v1/styles/middle.css
>  	cursor: pointer;
cursor обычно пишут для самого элемента, а не в :hover

2020-05-23 08:06 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<a href="#"> <nav class="page grey"> </nav> </a>
Ок, спасибо за решение, эта конструкция жестче и двигать ее легче

2020-05-23 08:06 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +						<label for="email"> <div class="button black lbl">fill button  </div></label>
Сделал

2020-05-23 08:06 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +				<a href="#"><nav class="page white"></nav></a>
сделал

2020-05-23 08:10 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +		<main class="articles_low">
сделано

2020-05-23 08:13 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/middle.css
> +	content: 'ᐳ ᐳ'; }
от старой версии осталось, с padding elements, убрал

2020-05-23 08:14 UTC, fineshtein commented on IcomingTest_HTML_v1/styles/middle.css
>  	cursor: pointer;
сделано

2020-05-23 08:14 UTC, fineshtein commented on IcomingTest_HTML_v1/index.html
> +						<label for="email"> <div class="button black lbl">fill button  </div></label>
сделано

2020-05-23 08:22 UTC, fineshtein commented
**Спасибо, Станислав, хороший рецензент!**

2020-05-24 21:31 UTC, Beeinterns approved these changes
Хорошо, можно выкатывать!

2020-06-19 05:54 UTC, closed without merging